added env variables

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Install zip tool
-        uses: montudor/action-zip@v1
+        run: sudo apt-get install -y zip
 
       - name: Install or Update AWS CLI
         run: |
@@ -29,23 +29,24 @@ jobs:
         run: |
             MAX_RETRIES=5
             RETRY_DELAY=10
-      
+
             for dir in ./lambdaFunctions/*/; do
               CONFIG_FILE="${dir}config.json"
-      
+
               # Read configuration variables
               FUNCTION_NAME=$(jq -r '.functionName' "$CONFIG_FILE")
               RUNTIME=$(jq -r '.runtime' "$CONFIG_FILE")
               TIMEOUT=$(jq -r '.timeout' "$CONFIG_FILE")
               MEMORY_SIZE=$(jq -r '.memorySize' "$CONFIG_FILE")
+              ENV_VARS=$(jq -r '.environmentVariables | to_entries | map("\(.key)=\(.value)") | join(",")' "$CONFIG_FILE")
               SQS_ENABLED=$(jq -r '.sqsTrigger.enabled' "$CONFIG_FILE")
-      
+
               echo "Deploying $FUNCTION_NAME"
-      
+
               # Create ZIP file
               zip -r "${FUNCTION_NAME}.zip" "${dir}"
-              sleep 5  # Sleep after creating ZIP
-      
+              sleep 5
+
               # Retry logic for updating function code
               attempt=0
               while [ $attempt -lt $MAX_RETRIES ]; do
@@ -57,38 +58,47 @@ jobs:
                   echo "Successfully updated function code for $FUNCTION_NAME"
                   break
                 fi
-      
-                attempt=$((attempt + 1))
-                echo "Update failed, retrying... ($attempt/$MAX_RETRIES)"
-                sleep $RETRY_DELAY
-              done
-              sleep 5  # Sleep after updating function code
-      
-              # Retry logic for updating function configuration
-              attempt=0
-              while [ $attempt -lt $MAX_RETRIES ]; do
-                aws lambda update-function-configuration \
-                  --function-name "$FUNCTION_NAME" \
-                  --runtime "$RUNTIME" \
-                  --timeout "$TIMEOUT" \
-                  --memory-size "$MEMORY_SIZE"
-                
-                if [ $? -eq 0 ]; then
-                  echo "Successfully updated function configuration for $FUNCTION_NAME"
-                  break
-                fi
-      
+
                 attempt=$((attempt + 1))
                 echo "Update failed, retrying... ($attempt/$MAX_RETRIES)"
                 sleep $RETRY_DELAY
               done
               sleep 5
-      
+
+              # Retry logic for updating function configuration
+              attempt=0
+              while [ $attempt -lt $MAX_RETRIES ]; do
+                if [ -n "$ENV_VARS" ]; then
+                  aws lambda update-function-configuration \
+                    --function-name "$FUNCTION_NAME" \
+                    --runtime "$RUNTIME" \
+                    --timeout "$TIMEOUT" \
+                    --memory-size "$MEMORY_SIZE" \
+                    --environment "Variables={$ENV_VARS}"
+                else
+                  aws lambda update-function-configuration \
+                    --function-name "$FUNCTION_NAME" \
+                    --runtime "$RUNTIME" \
+                    --timeout "$TIMEOUT" \
+                    --memory-size "$MEMORY_SIZE"
+                fi
+
+                if [ $? -eq 0 ]; then
+                  echo "Successfully updated function configuration for $FUNCTION_NAME"
+                  break
+                fi
+
+                attempt=$((attempt + 1))
+                echo "Update failed, retrying... ($attempt/$MAX_RETRIES)"
+                sleep $RETRY_DELAY
+              done
+              sleep 5
+
               # Add SQS Trigger if enabled
               if [ "$SQS_ENABLED" = "true" ]; then
                 EVENT_SOURCE_ARN=$(jq -r '.sqsTrigger.eventSourceArn' "$CONFIG_FILE")
                 BATCH_SIZE=$(jq -r '.sqsTrigger.batchSize' "$CONFIG_FILE")
-      
+
                 aws lambda create-event-source-mapping \
                   --function-name "$FUNCTION_NAME" \
                   --batch-size "$BATCH_SIZE" \
